[project]
name = "blackjack-engine"
version = "0.1.0"
description = "Blackjack engine for Group 4 course project"
readme = "README.md"
authors = [
    { name = "pengchong", email = "leo.zhao@student.ie.edu" },
    { name = "", email = "" },
    { name = "", email = "" },
    { name = "", email = "" },
    { name = "", email = "" },
    { name = "", email = "" }
]
requires-python = ">=3.9"
dependencies = [
    "streamlit>=1.50.0",
]

[project.urls]
Homepage = "https://github.com/pengchongzhao1113/blackjack-engine"

[build-system]
requires = ["uv_build>=0.9.22,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
