[project]
name = "blackjack-engine"
version = "0.1.1"
description = "Blackjack engine for Group 4 course project"
readme = "README.md"
authors = [
    { name = "Group 4 Team" }
]
requires-python = ">=3.9"
license = { text = "MIT" }
dependencies = [
    "streamlit>=1.50.0",
]

[project.urls]
Homepage = "https://github.com/pengchong1113/blackjack_engine"

[tool.uv]
package = true

[tool.uv.sources]
blackjack_engine = { path = "src/blackjack_engine" }

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["uv_build>=0.9.22,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
